- name: Create supervisor_etc in {{ supervisor_etc }}
  file: dest={{ supervisor_etc }} state=directory

- name: Create supervisor_var in {{ supervisor_var }}
  file: dest={{ supervisor_var }} state=directory

- name: Create supevisor_programs in {{ supervisor_programs }}
  file: dest={{ supervisor_programs }} state=directory

- name: Template supervisord.conf
  template: src=supervisord.conf.j2 dest="{{ supervisor_etc }}/supervisord.conf"

- name: Check if supervisord is already running
  shell: netstat -tunlp | grep ":{{ supervisor_port }}"
  register: supervisor_sock
  failed_when: "'FAILED' in supervisor_sock.stderr"

- name: Run supervisord
  shell: "{{ supervisor_bin }}/supervisord -c {{ supervisor_etc }}/supervisord.conf"
  when: supervisor_sock.stdout == ""
