- name: Create downloads directory
  local_action: file
  args:
    dest: "{{ downloads }}"
    state: directory

- name: Create directories for jdk
  file: dest={{ jdk_root }} state=directory

- name: Download jdk
  become: False
  run_once: True
  local_action: get_url
  args:
    url: "{{ jdk_download_url }}"
    dest: "{{ downloads }}/{{ jdk_filename }}"
    #headers:
    #  Cookie: oraclelicense=accept-securebackup-cookie

- name: Unarchive jdk
  unarchive:
    src: "{{ downloads }}/{{ jdk_filename }}"
    dest: "{{ jdk_root }}"
    extra_opts:
      --strip-components=1
