jdk_root: "{{ ansible_env.HOME }}/jdk"
jdk_version: '8u212b03'
jdk_filename_unarchive: "jre-{{ jdk_version }}-linux-x64"
jdk_filename: "{{ jdk_filename_unarchive }}.tar.gz"
jdk_mirror: http://download.oracle.com/otn-pub/java/jdk/
jdk_download_url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03/OpenJDK8U-jdk_x64_linux_hotspot_8u212b03.tar.gz
#jdk_download_url: http://download.oracle.com/otn/java/jdk/8u211-b12/478a62b7d4e34b78b671c754eaaf38ab/jdk-8u211-linux-x64.tar.gz

downloads: "{{ playbook_dir }}/downloads"
