- name: Download derby
  become: False
  run_once: True
  local_action: get_url
  args:
    url: "{{ derby_url }}"
    dest: "{{ downloads }}"
    checksum: md5:{{ derby_md5 }}

- name: Unarchive derby
  unarchive:
    src: "{{ downloads }}/{{ derby_url | basename }}"
    dest: "{{ tomcat_base }}/{{ tomcat_name }}/lib"
    exclude:
      - derby.war
      - README.htm
    extra_opts:
      - --strip-components=2

- name: Add ResourceLink to context.xml
  lineinfile:
    path: "{{ tomcat_base }}/{{ tomcat_name }}/conf/context.xml"
    insertbefore: </Context>
    line: '<ResourceLink global="jdbc/adminDB" name="jdbc/adminDB" type="javax.sql.DataSource"/>'
