- name: Global configuration
  hosts: all
  become: True
  tasks:
    - name: Install packages
      yum: name={{ item }} state=present
      with_items: [libselinux-python]

    - name: Add esgf.test.es to /etc/hosts
      become: True
      lineinfile: path=/etc/hosts line="172.28.128.3     esgf.test.es"

- name: Provision gateway
  hosts: gateway
  become: True
  tasks:
    - name: Copy httpd.conf (excludes WSGI stuff)
      copy: src=esgf-httpd.conf dest={{ httpd_conf_file }}

- name: Provision backends
  hosts: backend
  tasks:
    - name: Create datasets directory
      become: True
      file: state=directory path=/esg/data owner=vagrant group=vagrant

      #    - name: Install openjdk (required for keytool)
      #      become: True
      #      yum: state=present name=java-1.8.0-openjdk
      #
      #    - name: Copy hostcert.pem
      #      copy: src=/etc/certs/hostcert.pem dest=/home/vagrant/miniconda/envs/f2f/opt/hostcert.pem
      #
        #    - name: Install pyexpect
        #      pip:
        #        name: pexpect
        #        executable: "{{ miniconda_prefix }}/envs/{{ miniconda_env.name }}/bin/pip"
        #
        #    - name: Add hostcert.pem to miniconda cacerts
        #      expect:
        #        command: keytool -import -trustcacerts -alias smg -keystore /home/vagrant/miniconda/envs/f2f/jre/lib/security/cacerts -file /home/vagrant/miniconda/envs/f2f/opt/hostcert.pem
        #        responses:
        #          password: "changeit"
        #          Trust: "yes"
        #      environment:
        #        PYTHONPATH: "{{ miniconda_prefix }}/envs/{{ miniconda_env.name }}/lib/python2.7/site-packages/"
        #      register: keytool_cmd
        #      failed_when: keytool_cmd.rc > 1
        #      ignore_errors: True # Avoid error if alias already exists
