- name: Common provision for servers and L.B.
  hosts: 
    - all
  become: True
  tasks:
    - name: Install epel repository
      yum:
        name: epel-release
        state: present

    - name: Install software
      yum:
        name:
          - net-tools
          - tcpdump
          - iperf
          - htop
        state: present


- name: Provision servers
  hosts: tds
  become: True
  gather_facts: False
  tasks:
    - yum:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip

- name: Provision load-balancer
  hosts: gateways
  become: True
  gather_facts: False
  tasks:
    - name: Install software
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - "@Development Tools"
        - openssl-devel
        - zlib-devel
        - pcre-devel
