# httpd
httpd_root: "{{ miniconda_prefix }}/envs/{{ miniconda_env.name }}/opt/httpd"
httpd_htdocs: "{{ httpd_root }}/htdocs"
httpd_conf: "{{ httpd_root }}/conf"
httpd_conf_file: "{{ httpd_conf }}/httpd.conf"

# jdk
jdk_root: "{{ miniconda_prefix }}/envs/{{ miniconda_env.name }}/jre"

# mod_jk
mod_jk_conf: "{{ httpd_root }}/conf.d"
mod_jk_shm: "{{ httpd_root }}/logs/mod_jk.shm"
mod_jk_log: "{{ httpd_root }}/logs/mod_jk.log"
mod_jk_status: "{{ mod_jk_conf }}"

# supervisor
supervisor_home: "{{ miniconda_prefix }}/envs/{{ miniconda_env.name }}"
supervisor_bin: "{{ supervisor_home }}/bin"
supervisor_etc: "{{ supervisor_home }}/etc/supervisord"
supervisor_var: "{{ supervisor_home }}/var"
supervisor_programs: "{{ supervisor_etc }}/conf.d"

# tomcat
tomcat_home: "{{ miniconda_prefix }}/envs/{{ miniconda_env.name }}/opt/apache-tomcat"
tomcat_base: "{{ miniconda_prefix }}/envs/{{ miniconda_env.name }}/opt/instances"
