nginx_url_prefix: http://nginx.org/download
nginx_version: nginx-1.14.0
nginx_filename: "{{ nginx_version ~ '.tar.gz' }}"
nginx_directory: "{{ ansible_env.HOME ~ '/nginx_install' }}"
nginx_configure: "--without-http_rewrite_module --without-http_gzip_module --prefix={{ nginx_root }} --with-pcre"
nginx_root: "{{ ansible_env.HOME ~ '/nginx' }}"
nginx_static: "{{ nginx_root ~ '/static' }}"
nginx_bin: "{{ nginx_root ~ '/sbin/nginx' }}"
nginx_conf: "{{ nginx_root ~ '/conf/nginx.conf' }}"

downloads: "{{ playbook_dir }}/downloads"
