- name: Export variables
  set_fact:
    haproxy_conf: "{{ haproxy_conf }}"
    ansible_become: "{{ ansible_become | default(False) }}"

- name: Add configuration file
  template:
    src: haproxy/haproxy.cfg.j2
    dest: "{{ haproxy_conf }}"
