- import_tasks: httpd/httpd.yml

- name: Set modjk load balancer facts
  set_fact:
    ansible_become: "{{ ansible_become | default(False) }}"
    mod_jk_conf: "{{ mod_jk_conf }}" # workers need to be registered in mod_jk.workers file
  tags: always

- name: Create {{ mod_jk_conf }}
  file: state=directory path="{{ mod_jk_conf }}"

- name: Reference mod_jk files from httpd.conf
  lineinfile: path="{{ httpd_conf_file }}" line="Include {{ mod_jk_conf }}/*.conf"

- name: Template mod_jk conf files
  template: src=modjk/{{ item }}.j2 dest="{{ mod_jk_conf }}/{{ item }}"
  with_items: [mod_jk.conf, mod_jk.workers, mod_jk.urimaps]

- name: Create password for proxy status web pages
  htpasswd: path="{{ mod_jk_status }}/.htpasswd" username="{{ mod_jk_status_user }}" password="{{ mod_jk_status_passwd }}"
  when:  mod_jk_status_user is defined and mod_jk_status_passwd is defined
