- name: Install HAProxy
  become: True
  package:
    name: haproxy
    state: present
 
- name: Copy error files
  copy:
    src: errors
    dest: "{{ haproxy_root }}"

- name: Check HAProxy exec file
  command: "which haproxy"
  register: reg

- name: Set variable for HAProxy's executable
  set_fact:
    haproxy_bin: "{{ reg.stdout }}"
