- name: Clone TAP subversion repository
  local_action: subversion repo=https://meteo.unican.es/svn/repos/meteo/software/tap dest={{ downloads }}
  run_once: True
  vars:
    ansible_become: False
  when: tap_build=="svn"

- name: Build TAP
  local_action: command mvn package chdir={{ downloads }}/tap
  run_once: True
  vars:
    ansible_become: False
  when: tap_build=="svn"

- name: Create {{ tap_context }} dir
  file: state=directory path={{ tomcat_base }}/{{ tomcat_name }}/webapps/{{ tap_context }}

- name: Unarchive udg-tap.war from build
  unarchive: src={{ downloads }}/tap/target/udg-tap.war dest={{ tomcat_base }}/{{ tomcat_name }}/webapps/{{ tap_context }}
  when: tap_build=="svn"

- name: Unarchive udg-tap.war from file
  unarchive: src=udg-tap.war dest={{ tomcat_base }}/{{ tomcat_name }}/webapps/{{ tap_context }}
  when: tap_build=="local"

- name: Template global_variables.properties
  template:
    src: global_variables.properties.j2
    dest: "{{ tomcat_base }}/{{ tomcat_name }}/webapps/{{ tap_context }}/WEB-INF/classes/global_variables.properties"

- include_tasks: worker/modproxy.yml
  when: worker is defined
#################### Supervisord ####################
#- include_tasks: supervisor_configuration.yml
#  with_items: "{{ tap_instances }}"
