- name: Clone TAP subversion repository
  local_action: subversion repo=https://meteo.unican.es/svn/repos/meteo/software/tap dest={{ downloads }}
  run_once: True
  vars:
    ansible_become: False
  when: tap_build=="svn"

- name: Build TAP
  local_action: command mvn package chdir={{ downloads }}/tap
  run_once: True
  vars:
    ansible_become: False
  when: tap_build=="svn"

- name: Copy udg-tap.war from build
  copy: src={{ downloads }}/tap/target/udg-tap.war dest={{ tomcat_base }}/{{ tomcat_name }}/webapps/udg-tap.war
  when: tap_build=="svn"

- name: Copy udg-tap.war from file
  copy: src=udg-tap.war dest={{ tomcat_base }}/{{ tomcat_name }}/webapps/udg-tap.war
  when: tap_build=="local"

- include_tasks: worker/modproxy.yml
  when: worker is defined
#################### Supervisord ####################
#- include_tasks: supervisor_configuration.yml
#  with_items: "{{ tap_instances }}"
