- name: Clone TAP subversion repository
  local_action: subversion repo=https://meteo.unican.es/svn/repos/meteo/software/tap dest={{ downloads }}
  run_once: True
  vars:
    ansible_become: False
  when: tap_download

- name: Build TAP
  local_action: command mvn package chdir={{ downloads }}/tap
  run_once: True
  vars:
    ansible_become: False
  when: tap_download

- name: Create {{ tap_context }} dir
  file: state=directory path={{ tomcat_base }}/{{ tomcat_name }}/webapps/{{ tap_context }}

- name: Unarchive udg-tap.war from build
  unarchive: src={{ tap_war }} dest={{ tomcat_base }}/{{ tomcat_name }}/webapps/{{ tap_context }}

- name: Template global_variables.properties
  template:
    src: global_variables.properties.j2
    dest: "{{ tomcat_base }}/{{ tomcat_name }}/webapps/{{ tap_context }}/WEB-INF/classes/global_variables.properties"

#################### Supervisord ####################
#- include_tasks: supervisor_configuration.yml
#  with_items: "{{ tap_instances }}"
