# Control Tomcat instances with supervisord
- name: Create tomcat instances configuration file
  template:
    src: supervisor_wrapper.sh.j2
    dest: "{{ tomcat_base }}/{{ item.name }}/supervisor_wrapper.sh"
    mode: "u=rwx,g=rx,o=rx"

- name: Create tomcat instances configuration to supervisord 
  template:
    src: tomcat.conf.j2
    dest: "{{ supervisor_programs }}/{{ item.name }}.conf"
  register: tomcat_conf_supervisord

# Reread supervisord configuration and add tds_{{ intance.base_port }} program to supervisord
- name: Add tds_instance programmes to supervisord
  supervisorctl:
    name: "{{ item.name }}"
    state: present
    supervisorctl_path: "{{ venv_home }}/bin/supervisorctl"
    config: "{{ supervisor_etc }}/supervisord.conf"
    username: "{{ supervisor_user | default(omit) }}"
    password: "{{ supervisor_password | default(omit) }}"
    server_url: "http://localhost:{{ supervisor_port }}"
  when: tomcat_conf_supervisord.changed
