- name: Add worker to the modjk load balancer
  blockinfile:
    marker: "# {mark} {{ worker.route }}"
    path: "{{ hostvars[load_balancer].mod_jk_conf }}/mod_jk.workers"
    block: |
      worker.{{ worker.route }}.type=ajp13
      worker.{{ worker.route }}.host={{ worker.host | default(ansible_hostname) }}
      worker.{{ worker.route }}.port={{ worker.port | default(tomcat_ajp_port) }}
  delegate_to: "{{ load_balancer }}"
  vars:
    ansible_become: "{{ hostvars[load_balancer].ansible_become | default(False) }}" # depends on how httpd was installed

- name: Add worker to the modjk lb worker
  lineinfile:
    dest: "{{ hostvars[load_balancer].mod_jk_conf }}/mod_jk.workers"
    state: present
    line: worker.{{ item }}.balance_workers={{ worker.route }}
  delegate_to: "{{ load_balancer }}"
  vars:
    ansible_become: "{{ hostvars[load_balancer].ansible_become | default(False) }}" # depends on how httpd was installed
  with_items: "{{ worker.clusters }}"
