- name: Set jvmRoute in tomcats
  replace:
    path: "{{ tomcat_base }}/{{ tomcat_name }}/conf/server.xml"
    regexp: "<Engine(?!(.*)jvmRoute)(.*)>"
    replace: <Engine\2 jvmRoute="{{ worker.route }}">
  when: hostvars[load_balancer].lb_type in ["modjk", "modproxy"]

- name: Add worker to the load balancer
  include_tasks: "{{ hostvars[load_balancer].lb_type }}.yml"
  with_items: "{{ ansible_play_batch }}"
  when: "hostvars[host_item].inventory_hostname == inventory_hostname"
  loop_control:
    loop_var: host_item
