- hosts: localhost
  vars:
    root: "{{ playbook_dir }}/sandbox"
    ansible_python_interpreter: /usr/bin/python3 # required if using apt packages
    tomcat_home: "{{ root }}/tomcat"
    tomcat_base: "{{ root }}"
  roles:
    - role: supervisord-ubuntu
    - role: jdk-source
    - role: tomcat-source
    - role: tds
      # These are role defaults, they are showed here for illustration
      # You can tune these paremeters to suit your needs
      tomcat_name: tomcat
      tomcat_http_port: 8080
      tomcat_shutdown_port: 8005
      tomcat_Xmx: 4096m
      tomcat_Xms: 512m
      tds_version: 5.0.0-beta6
      tds_content: "{{ tomcat_base }}/{{ tomcat_name }}/content/thredds"
      tds_context: thredds
  tasks:
    - import_tasks: ../../utils/tomcat-service.yml

    - name: Clean
      file: path={{ root }} state=absent
      tags: [never, purge, clean]

    - name: Purge
      file: path={{ downloads }} state=absent
      tags: [never, purge]
