- hosts: localhost
  vars:
    root: "{{ playbook_dir }}/sandbox"
    ansible_python_interpreter: /usr/bin/python3 # required if using apt packages
    jdk_root: "{{ root }}/jdk"
    tomcat_home: "{{ root }}/tomcat"
    tomcat_base: "{{ root }}"
    tomcat_webapps: [tds]
    tomcat_Xmx: 2048m
    tomcat_Xms: 512m

    # SSL example, using keystore ../../server.p12
    ssl: True
    tds_useSSL: True
    tds_sslPort: "{{ tomcat_ssl_port }}"
    tomcat_ssl_connector: |
      <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
                 maxThreads="150" SSLEnabled="true" relaxedQueryChars="[:]">
        <SSLHostConfig>
          <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
                       certificateKeystorePassword="coches1"
                       type="RSA" />
        </SSLHostConfig>
      </Connector>

  roles:
    - role: jdk-source
    - role: tomcat-source
    - role: tomcat
  tasks:
    - name: Copy keystore
      copy: src=../../server.p12 dest={{ tomcat_base }}/{{ tomcat_name }}/conf/localhost-rsa.jks
      when: ssl is defined and ssl

    - import_tasks: ../../utils/tomcat-service.yml

    - name: Wait for tds to initialize
      wait_for: path={{ tds_content }}/public/testdata

    - name: Utility to debug a ncml file
      when: ncml is defined
      block:
      - name: Copy {{ ncml }}
        copy: src={{ ncml }} dest={{ tds_content }}/public/testdata/{{ ncml }}

      - name: Include ncml file in root catalog
        lineinfile:
          path: "{{ tds_content }}/catalog.xml"
          insertbefore: </catalog>
          line: <dataset name="ncml" ID="ncml" serviceName="all" urlPath="test/{{ ncml }}" />

      - import_tasks: ../../utils/tomcat-service.yml

    - name: Clean
      file: path={{ root }} state=absent
      tags: [never, purge, clean]

    - name: Purge
      file: path={{ downloads }} state=absent
      tags: [never, purge]
