downloads: "{{ playbook_dir }}/downloads"

# tomcat
tomcat_cluster: False
tomcat_manager: "" # memcached
tomcat_service: "" # systemd, supervisord

tomcat_name: tomcat
tomcat_webapps: []
tomcat_route: "{{ ansible_hostname }}{{ tomcat_name }}"
tomcat_http_port: 8080
tomcat_ssl_port: 8443
tomcat_ajp_port: 8009
tomcat_shutdown_port: 8005

# JVM opts
tomcat_Xms: 512m
tomcat_Xmx: 4096m

tomcat_connectors: |
  <Connector port="{{ tomcat_http_port }}" protocol="HTTP/1.1" connectionTimeout="20000"
             redirectPort="{{ tomcat_ssl_port }}"/>
  <Connector port="{{ tomcat_ajp_port }}" protocol="AJP/1.3" />
  <!--<Connector port="{{ tomcat_ssl_port }}" protocol="org.apache.coyote.http11.Http11NioProtocol"
             maxThreads="150" SSLEnabled="true">
    <SSLHostConfig>
      <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
                   certificateKeystorePassword="changeit"
                   type="RSA" />
    </SSLHostConfig>
  </Connector>-->
