downloads: "{{ playbook_dir }}/downloads"

# tomcat
tomcat_cluster: False
tomcat_manager: "" # memcached
tomcat_service: "" # systemd, supervisord

tomcat_name: tomcat
tomcat_webapps: []
tomcat_route: "{{ ansible_hostname }}{{ tomcat_name }}"
tomcat_http_port: 8080
tomcat_ajp_port: 8009
tomcat_shutdown_port: 8005
tomcat_ssl_port: 8443
tomcat_ssl_protocol: org.apache.coyote.http11.Http11Nio2Protocol
tomcat_ssl_maxThreads: 200
tomcat_ssl_scheme: https
tomcat_ssl_secure: true
tomcat_ssl_SSLEnabled: true
tomcat_ssl_clientAuth: false
tomcat_ssl_sslProtocol: TLS

# JVM opts
tomcat_Xms: 512m
tomcat_Xmx: 4096m
