- name: Replace tomcat@.service
  become: True
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/multi-user.target.wants/tomcat@{{ tomcat_name }}.service

- name: Reload systemd daemon
  become: True
  command: systemctl daemon-reload
