- name: Deploy load balancers
  hosts: lbs
  vars:
    httpd_root: /etc/httpd
    httpd_conf_file: /etc/httpd/conf/esgf-httpd.conf
    httpd_version: 2.2.15
  roles:
    - role: load-balancer
      lb_type: modproxy
      clusters:
        - name: data
          services: [dodsC, fileServer, dap4, ncss]
        - name: catalog
          services: [catalog]
  pre_tasks:
    # spock is supposed to have an ESGF node installed but lxc container is empty
    - name: Install httpd in lxd container
      include_role: name=httpd-centos7
      when: "'spock' != inventory_hostname"

    - name: Copy esgf-httpd.conf with /thredds disabled
      copy: src=esgf-httpd.conf dest=/etc/httpd/conf/esgf-httpd.conf

- name: Deploy workers
  hosts: workers
  vars:
    jdk_root: "{{ ansible_env.HOME }}/deployment/jdk"
    tomcat_home: "{{ ansible_env.HOME }}/deployment/tomcat"
    tds_root_catalog: catalog.xml
  roles:
    - role: jdk-source
    - role: tomcat-source
    - role: tds
      tomcat_name: i1
      tomcat_http_port: 8080
      tomcat_ajp_port: 8008
      tomcat_shutdown_port: 8005
      tds_melody:
        port: "{{ tomcat_http_port }}"
      worker:
        host: "{{ inventory_hostname }}"
        route: "{{ inventory_hostname }}-tds1"
        clusters: [catalog]
    - role: tds
      tomcat_name: i2
      tomcat_http_port: 8081
      tomcat_ajp_port: 8018
      tomcat_shutdown_port: 8006
      tds_melody:
        port: "{{ tomcat_http_port }}"
      worker:
        host: "{{ inventory_hostname }}"
        route: "{{ inventory_hostname }}-tds2"
        clusters: [data]
  pre_tasks:
    - name: Find catalogs
      run_once: True
      local_action:
        module: find
        paths: catalogs
      register: catalogs
      tags: catalogs

    - name: Add catalog refs
      run_once: True
      local_action:
        module: lineinfile
        path: "{{ tds_root_catalog }}"
        insertbefore: </catalog>
        line: '  <catalogRef xlink:title="{{ (item.path|basename|splitext)[0] }}" xlink:href="{{ item.path }}" name="" />'
      with_items: "{{ catalogs.files }}"
      tags: catalogs
  tasks:
    - name: Copy catalogs
      copy: src=catalogs dest={{ tomcat_base }}/{{ item }}/content/thredds
      with_items: [i1, i2]
      tags: catalogs

    - import_tasks: ../../utils/tomcat-service.yml
      vars:
        tomcats: [i1, i2]

- name: Restart load balancer
  hosts: lbs
  tasks:
    - name: Restart httpd
      service: name=httpd state=restarted
      tags: restart
