- name: Create downloads directory
  file: dest={{ downloads }} state=directory

- name: Install development packages
  become: True
  yum: state=present name="@Development tools"
  when: mod_jk_dependencies

- name: Install httpd-devel
  become: True
  yum: state=present name=httpd-devel
  when: mod_jk_dependencies

- name: Download mod_jk
  become: False
  run_once: True
  local_action: get_url
  args:
    url: "{{ mod_jk_download_url }}"
    dest: "{{ downloads }}/{{ mod_jk_filename }}"

- name: Create mod_jk_src directory
  file: path={{ mod_jk_src }} state=directory
  
- name: Unarchive mod_jk
  unarchive: src={{ downloads }}/{{ mod_jk_filename }} dest={{ mod_jk_src }}

- name: Configure mod_jk
  shell: "./configure --with-apxs=$(which apxs) {{ mod_jk_configure | default('') }}"
  args:
    chdir: "{{ mod_jk_src }}/{{ mod_jk_filename_unarchive }}/native"

- name: Configure and install mod_jk
  shell: "{{ item }}"
  args:
    chdir: "{{ mod_jk_src }}/{{ mod_jk_filename_unarchive }}/native"
  with_items:
    - /usr/bin/make
    - /usr/bin/make install
