- name: Add worker to the modproxy lb worker
  blockinfile:
    dest: "{{ hostvars[load_balancer].modproxy_conf }}"
    insertafter: <Proxy \"balancer://{{ cluster }}\">
    marker: '#{mark} {{ cluster }}:{{ tap_worker.host | default(ansible_hostname) }}:{{ tap_worker.port | default(tomcat_ajp_port) }}'
    block: BalancerMember "ajp://{{ tap_worker.host | default(ansible_hostname) }}:{{ tap_worker.port | default(tomcat_ajp_port) }}" loadfactor={{ tap_worker.loadfactor | default(1) }} route={{ tomcat_route }}
  delegate_to: "{{ load_balancer }}"
  vars:
    ansible_become: "{{ hostvars[load_balancer].ansible_become | default(False) }}" # depends on how httpd was installed
  with_items: "{{ tap_worker.clusters }}"
  loop_control:
    loop_var: cluster
