haproxy_major_version: 1.8
haproxy_version: haproxy-1.8.12
haproxy_filename: "{{ haproxy_version ~ '.tar.gz' }}"
haproxy_url: "{{ 'http://www.haproxy.org/download/' ~ haproxy_major_version ~ '/src/' ~ haproxy_version ~ '.tar.gz' }}"
haproxy_directory: "{{ ansible_env.HOME ~ '/haproxy_install'}}"
haproxy_root: "{{ ansible_env.HOME ~ '/haproxy' }}"
haproxy_bin: "{{ haproxy_root ~ '/usr/local/sbin/haproxy' }}"
haproxy_conf_dir: "{{ haproxy_root ~ '/conf' }}"
haproxy_conf: "{{ haproxy_conf_dir ~ '/haproxy.cfg' }}"
haproxy_errors: "{{ haproxy_root ~ '/errors' }}"

downloads: "{{ playbook_dir }}/downloads"
