- name: Gather facts on all hosts
  hosts: all
  gather_facts: True

- name: Configure load balancer
  become: True
  hosts: gateways
  vars:
    vip: "{{ ansible_ens10.ipv4.address }}"
  roles:
    - role: yum
      dependencies: [ipvsadm]
    - role: source
      dependencies: [keepalived]
      tags: [keepalived]
    - role: keepalived
      tags: [keepalived]
  tasks:
    - name: Disable Reverse Path Filtering
      sysctl:
        name: "{{ item }}"
        value: 0
      with_items:
        - net.ipv4.conf.all.rp_filter
        - "net.ipv4.conf.{{ ansible_ens10.device }}.rp_filter"
          #- "net.ipv4.conf.{{ ansible_eth1.device }}.rp_filter"

- name: Configure servers
  hosts: tds
  vars:
    ansible_become_pass: ansible
    # required interface
    jdk_root: "{{ ansible_env.HOME }}/jdk"
    tomcat_home: "{{ ansible_env.HOME }}/tomcat"
    tomcat_base: "{{ ansible_env.HOME }}/instances"
    venv_home: "{{ ansible_env.HOME }}/virtualenv"
  roles:
    - role: source
      dependencies: [jdk, tomcat, supervisor]
      tags: [tds_deploy, jdk]
  # - role: yum
  #   dependencies: [memcached]
      tags: [tds_deploy]
    - role: tomcat-memcached
      instances: "{{ tds }}"
      tags: [tds_deploy]
    - role: supervisor-tds
      tags: [tds_deploy]
    - role: tds-keepalived
      tags: [keepalived]
      become: True
  tasks:
    - include_tasks: ../../../utils/test-authentication.yml
      vars:
        instances: "{{ tds }}"
      tags: [tds_deploy]

    - name: Start memcached
      command: memcached -d -u ansible
      tags: [tds_deploy]

    - name: start tds instances
      supervisorctl:
        name: "{{ item.name }}"
        state: started
        username: "{{ supervisor_user | default(omit) }}"
        password: "{{ supervisor_password | default(omit) }}"
        supervisorctl_path: "{{ supervisor_bin }}/supervisorctl"
      with_items: "{{ tds }}"
      tags: [tds_deploy]

    - name: restart tds instances
      supervisorctl:
        name: "{{ item.name }}"
        state: restarted
        username: "{{ supervisor_user | default(omit) }}"
        password: "{{ supervisor_password | default(omit) }}"
        supervisorctl_path: "{{ supervisor_bin }}/supervisorctl"
      with_items: "{{ tds }}"
      tags: [tds_deploy, restart, update_catalogs]

- name: Start keepalived
  hosts: gateways
  become: True
  tasks:
    - shell: "{{ keepalived_bin }} -f {{ keepalived_conf }}" 
  tags: [keepalived, start_keepalived]
