downloads_tmp: "{{ playbook_dir ~ '/downloads' }}"
keepalived_version: keepalived-2.0.10
keepalived_filename: "{{ keepalived_version ~ '.tar.gz' }}"
keepalived_url: "{{ 'http://www.keepalived.org/software/' ~ keepalived_filename }}"
keepalived_directory: "{{ ansible_env.HOME ~ '/' ~ keepalived_version }}"
keepalived_root: "{{ ansible_env.HOME ~ '/keepalived' }}"
keepalived_config_params: "{{ '--prefix=' ~ keepalived_root }}"
keepalived_config_file: "{{ keepalived_root ~ '/etc/keepalived/keepalived.conf' }}"
keepalived_bin: "{{ keepalived_root ~ '/sbin/keepalived' }}"
