- name: Set facts
  set_fact:
    haproxy_bin: "{{ haproxy_bin }}"

- name: Create downloads directory
  local_action: file
  args:
    dest: "{{ downloads }}"
    state: directory

- name: Create directory for HAProxy
  file:
    path: "{{ haproxy_directory }}"
    state: directory

- name: Download HAProxy
  run_once: True
  local_action: get_url
  args:
    url: "{{ haproxy_url }}"
    dest: "{{ downloads }}/{{ haproxy_filename }}"

- name: Unarchive HAProxy
  unarchive:
    src: "{{ downloads }}/{{ haproxy_filename }}"
    dest: "{{ haproxy_directory }}"

- name: Insert destiny directory in Makefile
  lineinfile:
    path: "{{ haproxy_directory }}/{{ haproxy_version }}/Makefile"
    regexp: '^DESTDIR ='
    line: 'DESTDIR = {{ haproxy_root }}'

- name: Compile source code
  make:
    chdir: "{{ haproxy_directory }}/{{ haproxy_version }}"
    params:
      TARGET=linux2628
      USE_PCRE=1
      USE_ZLIB=1
      USE_OPENSSL=1

- name: Install HAProxy
  make:
    chdir: "{{ haproxy_directory }}/{{ haproxy_version }}"
    target: install

- name: Create directory for configuration file
  file:
    path: "{{ haproxy_conf_dir }}"
    state: directory

- name: Copy error files
  copy:
    src: errors
    dest: "{{ haproxy_root }}"

